# Generated by Django 3.1.4 on 2021-06-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='company',
        ),
    ]
