# Generated by Django 3.1.4 on 2021-06-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210622_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_short_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
