# Generated by Django 3.1.4 on 2021-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_company_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=200, null=True)),
                ('social_media_link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
