# Generated by Django 3.1.4 on 2021-06-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_social_media_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='social_media_links',
            new_name='social_media_link',
        ),
    ]
