# Generated by Django 3.1.4 on 2021-06-22 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210622_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media_link',
            name='social_media_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static'),
            preserve_default=False,
        ),
    ]
