# Generated by Django 3.1.4 on 2021-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_social_media_link_social_media_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media_link',
            name='style',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
