# Generated by Django 3.1.4 on 2021-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_social_media_link_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_media_link',
            old_name='style',
            new_name='height',
        ),
        migrations.AddField(
            model_name='social_media_link',
            name='width',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
