# Generated by Django 3.1.4 on 2021-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210622_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
