# Generated by Django 3.1.4 on 2021-06-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210623_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='desc_width',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_width',
        ),
    ]
