# Generated by Django 3.1.4 on 2021-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210623_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
