# Generated by Django 3.1.4 on 2021-06-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210623_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
