# Generated by Django 3.1.4 on 2021-06-25 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210624_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
