# Generated by Django 3.1.4 on 2021-06-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_blog_data_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_data',
            name='date',
        ),
    ]
