# Generated by Django 3.1.4 on 2021-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_slider_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
