# Generated by Django 3.1.4 on 2021-06-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210625_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
