# Generated by Django 3.1.4 on 2021-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210625_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
