# Generated by Django 3.1.4 on 2021-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_site_site_description_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_description_footer',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
