# Generated by Django 3.1.4 on 2021-06-26 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210625_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
