# Generated by Django 3.1.4 on 2021-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_blog_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='date',
            field=models.DateField(),
        ),
    ]
