# Generated by Django 3.1.4 on 2021-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210626_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
