# Generated by Django 3.1.4 on 2021-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210626_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
