# Generated by Django 3.1.4 on 2021-06-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210626_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
