# Generated by Django 3.1.4 on 2021-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210626_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='code_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('e_mail', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
