# Generated by Django 3.1.4 on 2021-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210626_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
