# Generated by Django 3.1.4 on 2021-06-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210628_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='height',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='width',
        ),
    ]
