# Generated by Django 3.1.4 on 2021-07-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_arduino_project_about_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratch_project',
            name='about_3',
        ),
    ]
