# Generated by Django 3.1.4 on 2021-07-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_scratch_project_about_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_project',
            name='about_2',
        ),
        migrations.RemoveField(
            model_name='basic_project',
            name='about_3',
        ),
    ]
