# Generated by Django 3.1.4 on 2021-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20210818_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='scratch_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('code', models.TextField(max_length=100000, null=True)),
            ],
        ),
    ]
