# Generated by Django 3.1.4 on 2021-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_scratch_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scratch_code',
            old_name='link',
            new_name='apk_link',
        ),
        migrations.RenameField(
            model_name='scratch_code',
            old_name='code',
            new_name='code_image_link',
        ),
        migrations.AddField(
            model_name='scratch_code',
            name='project_embed_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='scratch_code',
            name='sb2_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
